### ISSUE TITLE
problem to run example 

### ISSUE THREAD

**Issue by irnb** [zeriontech/defi-sdk-py#3]
hi I wanna execute the examples and I get err 

>>> await defi_sdk.get_token_adapter_names()
SyntaxError: 'await' outside function

**Comment by irnb** [comment]
I can solve this 
solution :

```
>>> import asyncio
>>> from defisdk import DeFiSDK
>>> ETHEREUM_NODE_URL = 'https://eth-mainnet.zerion.io/'
>>> defi_sdk = DeFiSDK(ETHEREUM_NODE_URL)
>>> loop = asyncio.get_event_loop()
>>> data = loop.run_until_complete(defi_sdk.get_protocol_names())
>>> loop.close()
>>> data

```

**Comment by bashalex** [comment]
Hey @irnb!
Since the library interface is asynchronous, all the methods should be called from async functions.
Indeed, it should be done either by explicitly initializing event loop or using an interpreter such as ipython that does it under the hood.
